### ISSUE TITLE
Graphic Interface - Drafts and Ideas

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Arquisoft/viade_en3b#40]
I'm opening this issue to enable a place to post our **ideas and drafts for the graphic interface design**. As we said in the quality goals, our application must be usable, and that means that the graphic interface should be intuitive for the user to use the application.

First, this is my idea for the main screen of the application:
![boceto1_1](https://user-images.githubusercontent.com/56108450/75605432-1b47fc80-5ae3-11ea-93a3-90d31636ac51.jpg)

As you can see, my idea shows a screen divided in three diferentiated segments:

- **Left**: panel for the **user's account control**. This part should have the main information about the user that is logged in. Name, surname (or nickname), the number of routes he/she has done, the date of the last route... There we can put any information we consider useful to be displayed.

- **Center**: this is the main panel. Here, all the routes are displayed in a scrolled-down way. The user will be able to scroll down to see the main information of the routes he/she has done. Also, we should consider adding a **filter or search feature**, to facilitate the operation of searching for an specific route. Other filter options should be considered, like date, duration, length of the route, etc.

- **Right**: this is the **Friend panel**. Here, the user will see all its Friends. Just the basic information will be displayed. Also, an _Adding Friend_ feature should be considered.

**Comment by CarmenVigo** [comment]
Hi, I really liked your prototype.
I asked a few of our trustful beta users and they gave me ideas to improve our main screen application.
I'll explain the modifications first and then I'll upload the prototype, ok?
First, in the logged user info they said they'd rather have like the month overview. Then, in the centre area, they only wanted to have their own routes with the media display (so they do not need to enter the route in order to see photos). Lastly, in the friends' section, they wanted to have a display of their recent routes (the name and the map).
So... this is my screen (I hope it visualizes correctly):
![WhatsApp Image 2020-02-29 at 13 21 15](https://user-images.githubusercontent.com/57048900/75607537-6e787a00-5af8-11ea-9509-cec64790eb96.jpeg)
* Where it says Actividad Reciente in the friends' area I mean Friends' Activity.
* In the images carrousel I wanted to portrait the feature of seeing the media I mention.
Then, in the top right corner, I missed the notifications so I added the bell; and also the possibility of logging out.
What do you think? We probably still need to refine our main screen a little bit more. :)

**Comment by PabloCanalSuarez** [comment]
I find that version of the design interface really interesting, thanks for sharing it. 

I think your new way to display the routes is very useful, especially the media contents. Nevertheless, these features will be left until the last version of the application, as in the first prototype (v0.1) we will not show media contents at first (unless we have enough time to develop that feature).

**Comment by UO264850** [comment]
Hi, the prototypes look great, i have also asked users about the interfaces they are used to see, and the ones that they like. As the range of opinions was very wide, i resumed everything into 3 prototypes, which are the following: 

![viade1](https://user-images.githubusercontent.com/56356462/75707946-1f7d4100-5cc0-11ea-9937-9aea02e715e4.png)

![viade2](https://user-images.githubusercontent.com/56356462/75707952-21470480-5cc0-11ea-94dd-d709c9da585b.png)

![viade3](https://user-images.githubusercontent.com/56356462/75707957-24da8b80-5cc0-11ea-80be-bf668a09333d.png)

For the first week, I will start developing the prototype that Pablo has posted, as it has just the basic functionality, and later we can try to add the functionality that Carmen proposed to make the application more complete. If you disagree tell me as fast as posible to adapt the interface to everyone's taste.

**Comment by PabloCanalSuarez** [comment]
LGTM

**Comment by CarmenVigo** [comment]
LGTM 👍

**Comment by ElenaRodriguezRio** [comment]
LGTM :)

**Comment by PabloCanalSuarez** [comment]
Useful links to read and learn about Material-UI in React:

- https://github.com/mui-org/material-ui
- https://material-ui.com/es/getting-started/templates/ (very useful one, has the documentation about all components of Material-UI)

**Comment by PabloCanalSuarez** [comment]
This issue isn't used anymore
